name: crossplatform
description: An example of code sharing between Android, iOS, and Web that uses BLoC architecture.
version: 0.0.1
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/crossplatform

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.3.3
  args: ^1.5.0
  path: ^1.6.2
  shared_theme: ^0.1.2
  colorize: ^2.0.0